title: Jekyll URL Shortener
description: âœ‚ï¸ğŸ”— This is a template repository for making URL Shorteners with Jekyll and GitHub Pages. Create short URLs that can be easily shared, tweeted, or emailed to friends.
logo: /assets/img/logo.png
show_downloads: true
google_analytics:
theme: minima  # Ganti ke minima (built-in, fix error theme)
permalink: /:slug/
plugins:
  - jekyll-redirect-from
github: [metadata]
exclude:
  - README.md
  - LICENSE
  - CNAME
